name = "Sezon 4"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "377426b39efbf0c348940f2d537359647fc27bc00e28fc3bc8c7be7b0e4178f3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
