name = "Sezon 4"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d7c8ee511d12e441e90a03ea20cb0990e48fca30f2ba0f0a0bb522e25a6807d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
